package com.huixin.web.model;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.msg_type
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.send_user_id
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Integer sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.creat_time
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.send_time
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_send
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Integer isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_top
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_delete
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.msg_type
     *
     * @return the value of notice.msg_type
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.msg_type
     *
     * @param msgType the value for notice.msg_type
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.send_user_id
     *
     * @return the value of notice.send_user_id
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.send_user_id
     *
     * @param sendUserId the value for notice.send_user_id
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.creat_time
     *
     * @return the value of notice.creat_time
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.creat_time
     *
     * @param creatTime the value for notice.creat_time
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.send_time
     *
     * @return the value of notice.send_time
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.send_time
     *
     * @param sendTime the value for notice.send_time
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_send
     *
     * @return the value of notice.is_send
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Integer getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_send
     *
     * @param isSend the value for notice.is_send
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_top
     *
     * @return the value of notice.is_top
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_top
     *
     * @param isTop the value for notice.is_top
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_delete
     *
     * @return the value of notice.is_delete
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_delete
     *
     * @param isDelete the value for notice.is_delete
     *
     * @mbggenerated Tue Feb 14 14:27:03 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
    
    
    
    
    private String sendTime1;
    private String sendTime2;

	public String getSendTime1() {
		return sendTime1;
	}

	public void setSendTime1(String sendTime1) {
		this.sendTime1 = sendTime1;
	}

	public String getSendTime2() {
		return sendTime2;
	}

	public void setSendTime2(String sendTime2) {
		this.sendTime2 = sendTime2;
	}
    
	
	
	
}